### ISSUE TITLE
Traccia

### ISSUE THREAD

**Issue by iannellog** [leoairuf/solitario4re#1]
Allo scopo di consentire anche a Valerio e a me di seguire in background il progredire del progetto, potete caricare sul repository GitHub anche la traccia concordata con Marcello (e mantenerla aggiornata nel caso concordate modifiche con lui)?

**Comment by leoairuf** [comment]
Buonasera professore. Come ci ha chiesto abbiamo aggiunto la specifica del progetto e la manterremo aggiornata.
