### ISSUE TITLE
README.md da migliorare

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#10]
Il software prevede l'esecuzione condizionata dalla configurazione dei parametri di ingresso. Inserire nella documentazione visibile nel `README.md` le istruzioni per l'avvio dell'applicativo e riportare anche degli esempi per ognune delle possibili casistiche.

**Comment by LMarcoccia** [comment]
Buongiorno, abbiamo perfezionato il README.md e aggiunto le informazioni richieste.
