### ISSUE TITLE
Errore nel calcolo della probabilità

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#12]
La probabilità di riuscita del 2% circa fornita dal programma non è esatta. Il codice realizzato va analizzato attentamente e va scovato l'errore attualmente presente.

Verificare la possibilità di usare `pdb` per effettuare il debug riga per riga del codice.

**Comment by LMarcoccia** [comment]
Professore, abbiamo fatto controlli e verifiche su tutti i passaggi del programma e sui vari metodi di classe. Inoltre abbiamo giocato realmente le partite partendo dai risultati generati dai casi di test e non abbiamo riscontrato problemi. Onestamente non abbiamo idea di dove possa trovarsi il problema. Lei ha scoperto qualcosa?

**Comment by supix** [comment]
Guardate con più attenzione. Se proprio non riuscite ad utilizzare il debugger, usate a man bassa stampe durante il programma per verificare che il flusso dell'applicazione sia quello atteso.

**Comment by LMarcoccia** [comment]
Dovremmo aver trovato il problema: c'era un errore nella procedura di sostituzione delle carte. Ora il programma vince il 25% delle partite. Ci conferma il valore?
