### ISSUE TITLE
Separare il codice su più files

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#13]
L'approccio di scrivere tutto il codice in un unico file non è scalabile. Si pensi ad un programma costituito da centinaia di classi.

E' opportuno separare il progetto su più files. Una buona soluzione è utilizzare un file per ogni classe.

**Comment by LMarcoccia** [comment]
Pensavamo di creare un modulo in cui inserire tutto ciò che non fosse il corpo principale del codice e inserirlo nella repository, così da rendere più ordinato e leggibile il programma. Prima però vorremmo limare alcuni dettagli e concentrarci sulla risoluzione del problema della probabilità.

**Comment by LMarcoccia** [comment]
Abbiamo effettuato le modifiche richieste.
