### ISSUE TITLE
Utilizzare il branch develop

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#14]
git incoraggia l'esecuzione di commit piccoli e frequenti, in cui il messaggio di commit spiega bene cosa è stato fatto. Tali commit vanno fatti sul branch `develop` e, ogni volta che l'applicazione raggiunge uno stato _stabile_ e può essere distribuita all'utente, riversati sul branch `main`. Per riprendere ad utilizzare il branch `develop` provate a fare:

```
git checkout develop
git merge main
git push
```

Da quel momento potete fare commit sul branch `develop`:

```
git add .
git commit
git push
```
e quando volete sincronizzare il `main`:

```
git checkout main
git merge develop
git push
```

salvo poi riportarvi sul branch `develop` per continuare lo sviluppo:

```
git checkout develop
```

**Comment by supix** [comment]
Ho visto che avete correttamente riportato il branch `develop` al passo col `main`. E' strano comunque che `develop` stia un passetto indietro rispetto al `main`. Di solito sta sempre un po' avanti. Almeno finché non si fa merge da `develop` su `main` (pubblicazione nuova release), nel qual caso ritornano al passo. Salvo poi disallinearsi subito dopo perché il ramo `develop` riprende ad avanzare.

Provate a sviluppare sempre sul ramo `develop` ed usare il `main` solo per fare merge commit dal ramo `develop`.

**Comment by LMarcoccia** [comment]
Buonasera Professore, abbiamo sincronizzato i due branch. Metteremo come branch di default 'develop' per implementare le ultime modifiche.

**Comment by supix** [comment]
Non c'è bisogno di mettere `develop` come branch di default. Altrimenti gli utenti che si collegano al repository vedrebbero e scaricherebbero quel branch. L'importante è trovarsi sul branch `develop` in fase di sviluppo, e portarsi sul branch `main` solo per "rilasciare" versioni stabili.
