### ISSUE TITLE
Metodo di stampa del tavolo

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#15]
https://github.com/leoairuf/solitario4re/blob/9fd2adef5bad62d43d6121f0817c0545f4a16815/solitario.py#L92-L96

Con le righe indicate, il metodo `gioca_partita()` sta sostanzialmente ispezionando gli attributi della classe `Tavolo` per stamparli.

E' più corretto che la responsabilità della stampa del tavolo ce l'abbia la classe `Tavolo` stessa mediante un apposito metodo. In caso di eventuali future modifiche alla classe `Tavolo` non avrete l'obbligo (facile da dimenticare in programmi molto estesi) di cercare in giro frammenti di codice da modificare.

**Comment by LMarcoccia** [comment]
Buongiorno Professore, abbiamo dotato la classe 'Tavolo' di un metodo 'stampa_tavolo'. 
Le volevamo chiedere una cosa: negli scorsi giorni le abbiamo scritto una mail per informarla della nostra volontà di sostenere l'esame martedì. Se l'ha vista, ci conferma che possiamo farlo?
