### ISSUE TITLE
E' davvero così?

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#3]
https://github.com/leoairuf/solitario4re/blob/d916c35ef10a6cba6c2f4acbab7c14c85e518284/Spunti.txt#L2

**Comment by LMarcoccia** [comment]
In Python gli indici partono da zero, quindi nel solitario la prima carta (l'asso) occuperebbe la casella zero in un'ipotetica lista (ad esempio nel mazzo ordinato). Nel programma abbiamo considerato questo aspetto, quindi se si stampa la disposizione delle carte sul tavolo l'utente legge che una carta 'asso' ha valore 1 ma l'indice a essa corrispondente è zero.

**Comment by supix** [comment]
Ok. Va spiegata meglio allora. Da questa riga

https://github.com/leoairuf/solitario4re/blob/d916c35ef10a6cba6c2f4acbab7c14c85e518284/solitario.py#L90

si vede che l'asso vale 1.
Una volta risposto ad un Issue potete chiuderlo.
L'issue può essere automaticamente chiuso includendo [delle specifiche keyword](https://stackoverflow.com/a/60027286/1045789) nei messaggi di commit.

**Comment by LMarcoccia** [comment]
Va bene, toglieremo dalla repository il file spunti non aggiornato ed eventualmente specificheremo questo comportamento nel README.md.
