### ISSUE TITLE
Costrutto di selezione `if` con condizione booleana

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#4]
https://github.com/leoairuf/solitario4re/blob/d916c35ef10a6cba6c2f4acbab7c14c85e518284/solitario.py#L65

Questa sintassi può essere resa più sintetica e più leggibile.

[Vedi qua](https://stackoverflow.com/a/38423419/1045789).

Questo stesso problema è presente in molti punti del codice.

**Comment by LMarcoccia** [comment]
Ok, abbiamo sistemato questo problema.
