### ISSUE TITLE
Corretto uso del pattern Strategy

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#5]
https://github.com/leoairuf/solitario4re/blob/d916c35ef10a6cba6c2f4acbab7c14c85e518284/solitario.py#L114

Il [pattern Strategy](https://refactoring.guru/design-patterns/strategy/python/example) prevede una classe base Stategy e tante classi concrete quante sono le possibili strategie. Gli attuali metodi, dunque, devono essere trasformati in classi concrete.

Esempi di possibili strategie implementabili:

* associazione seme-riga casualmente calcolata ad inizio partita (già presente);
* associazione seme-riga statica (già presente);
* associazione seme-riga dinamica: la prima uscita di un seme va ad occupare la prima riga ancora libera.

Interessante verificare che la probabilità è indipendente dalla strategia selezionata.

**Comment by leoairuf** [comment]
Abbiamo aggiunto il pattern Strategy e abbiamo verificato che la probabilità di vittoria è indipendente dalla strategia utilizzata.

**Comment by supix** [comment]
Ok le due classi realizzate. Manca la terza strategia, che è capace di selezionare:

* la prima riga vuota (dall'alto) disponibile, per un seme mai visto prima;
* la riga già assegnata al seme, nel caso di seme già uscito in precedenza.

La strategia va pertanto interrogata in occasione della sistemazione _di ogni carta_ sul tavolo. Per realizzarla mettetevi nei panni di una persona che guarda la carta da deporre, guarda il tavolo, ci ragiona su e vi dice una cosa del tipo:- _"per questa carta usa la riga 3"_.

Va leggermente modificata la logica. La strategia non lavora una tantum all'inizio del gioco fissando tutte le associazioni riga-seme. Ma lavora ad ogni iterazione del gioco. E per farlo ha bisogno di _vedere_ la carta corrente e la situazione del tavolo. Questo implica una modifica al propotipo del metodo attualmente esistente (che dovrebbe cambiare anche nome). Andranno aggiunti i parametri utili al funzionamento della terza strategia. Quegli stessi parametri verranno in parte (o tutti) ignorati dalle altre due realizzazioni della strategia.

Questa issue andrebbe riaperta fino a completamento.

**Comment by leoairuf** [comment]
Buonasera professore, abbiamo aggiunto la strategia che associa i semi alle righe in modo dinamico. Pensavamo di dare all'utente la possibilità di selezionare in input la strategia con la quale effettuare la simulazione per il calcolo della probabilità di vittoria. Lei cosa ne pensa?

**Comment by supix** [comment]
Non c'è bisogno di far scegliere all'utente la strategia.
