### ISSUE TITLE
L'inizializzazione del tavolo è nel posto sbagliato

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#6]
Questo metodo

https://github.com/leoairuf/solitario4re/blob/d916c35ef10a6cba6c2f4acbab7c14c85e518284/solitario.py#L120

non dovrebbe far parte della strategia. L'unica responsabilità della strategia è comunicare al giocatore quale riga utilizzare per una carta di un dato seme. La strategia contiene quindi un unico metodo.

**Comment by LMarcoccia** [comment]
Abbiamo spostato 'disponi_carte' nella classe tavolo.
