### ISSUE TITLE
Costrutto di selezione `if` con rami troppo estesi

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#8]
https://github.com/leoairuf/solitario4re/blob/d916c35ef10a6cba6c2f4acbab7c14c85e518284/solitario.py#L242

I rami di un `if` non devono contenere più di poche righe.

Una soluzione può essere incapsulare in dei metodi il contenuto dei due rami.

Meglio ancora sarebbe creare due diverse classi per gestire le due modalità di esecuzione ed istanziare con un unico `if` iniziale quella di volta in volta utile.

**Comment by LMarcoccia** [comment]
Si, ne siamo consapevoli e uno dei prossimi step era proprio quello di compattare il codice definendo ulteriori function (ad esempio gioca_partita che incorpora tutto il codice necessario per svolgere una partita). Lo switch logico è ancora una bozza: vorremmo anche trovare ,se possibile, un metodo più elegante di un if come quello già incluso.
