### ISSUE TITLE
Responsabilità da riassegnare

### ISSUE THREAD

**Issue by supix** [leoairuf/solitario4re#9]
https://github.com/leoairuf/solitario4re/blob/d916c35ef10a6cba6c2f4acbab7c14c85e518284/solitario.py#L184

Più che dotare il `Giocatore` di un metodo `mazzetto_vuoto` sarebbe opportuno dotare il `Mazzo` di un metodo `vuoto`.

**Comment by LMarcoccia** [comment]
Ok, risolto.
